/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DockerController;
import files.Filenames;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import utils.Utils;

/**
 *
 * @author mo22
 */
public class View2 extends javax.swing.JFrame {
    private static final String WARNING_ICON_TEXT_NAME = "warning.png"; 
    /**
     * Creates new form View2
     */
    
    private View1 view1 = null;
    private Utils utils = null;
    private DockerController dockerController = null;

    public View2(Utils utils, DockerController dockerController, View1 view1) {
        initComponents();
        this.view1 = view1;
        this.dockerController = dockerController;
        this.utils = utils;
        this.utils.iconFitInLabel(jLabel1,WARNING_ICON_TEXT_NAME);
        this.utils.setVisible(NoInputWarningLabel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        InsertPswButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NoInputWarningLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        RepeatPasswordTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("To be able to use Super Docker tool on Linux, it required the root password:");

        InsertPswButton.setBackground(new java.awt.Color(0, 153, 204));
        InsertPswButton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        InsertPswButton.setText("Insert password");
        InsertPswButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertPswButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertPswButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N

        NoInputWarningLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setText("Password:");

        jLabel4.setText("Repeat Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsertPswButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NoInputWarningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordTextField)
                            .addComponent(RepeatPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                        .addGap(39, 39, 39)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RepeatPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoInputWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertPswButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertPswButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertPswButtonActionPerformed
        boolean passEncrypted = false;
        String passwordTextField = String.valueOf(PasswordTextField.getPassword());
        String repeatTextPassword = String.valueOf(RepeatPasswordTextField.getPassword());
        
        if(passwordTextField.length() < 1){
            NoInputWarningLabel.setText("Please, first insert the password!");
        } else {
            if((passwordTextField.length() > 0 && repeatTextPassword.length() > 0) && passwordTextField.equals(repeatTextPassword)){
                passEncrypted = dockerController.encryptAndSavePassword(passwordTextField);
            } else {
                NoInputWarningLabel.setText("Password does not match, please try again");
                utils.eraseTextField(Arrays.asList(this.PasswordTextField,this.RepeatPasswordTextField));     
            }
        }
        
        if(passEncrypted){
            this.setVisible(false);
            this.view1.dispose();
            new View1(); 
        }
    }//GEN-LAST:event_InsertPswButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertPswButton;
    private javax.swing.JLabel NoInputWarningLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JPasswordField RepeatPasswordTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
